services:
  mysql:
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1024M
        reservations:
          cpus: "0.25"
          memory: 256M
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  backend:
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: 1024M
        reservations:
          cpus: "0.5"
          memory: 512M
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  frontend-admin:
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
        reservations:
          cpus: "0.1"
          memory: 64M
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
